# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 12:06
from __future__ import unicode_literals

import apps.utils.django_.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0013_auto_20160923_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='backend',
            field=models.CharField(choices=[(b'bot', b'dbmail.backends.bot'), (b'mail', b'dbmail.backends.mail'), (b'push', b'dbmail.backends.push'), (b'sms', b'apps.notifications.backends.sms')], db_index=True, default=b'mail', editable=False, max_length=25, verbose_name='Backend'),
        ),
        migrations.AlterField(
            model_name='mailsubscription',
            name='address',
            field=models.CharField(db_index=True, help_text='Must be phone number/email/token', max_length=350, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='mailsubscription',
            name='backend',
            field=models.CharField(choices=[(b'dbmail.backends.mail', 'MailBox'), (b'apps.notifications.backends.sms', 'SMS'), (b'dbmail.backends.push', 'Push'), (b'dbmail.backends.bot', 'Bot')], default=b'dbmail.backends.mail', max_length=50, verbose_name='Backend'),
        ),
        migrations.AlterField(
            model_name='mailsubscription',
            name='data',
            field=apps.utils.django_.db.fields.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mailsubscription',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='category',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmail.MailCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='from_email',
            field=models.ForeignKey(blank=True, default=2, help_text='If not specified, then used default.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmail.MailFromEmail', verbose_name='Message from'),
        ),
    ]
