# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 12:06
from __future__ import unicode_literals

from dbmail.defaults import SIGNAL_CHOICES, _SIGNALS
from django.db import migrations, models

def make_signals_dynamic(apps, schema_editor):
    Signal = apps.get_model('dbmail', 'Signal')
    for module_path, signal_name in _SIGNALS:
        Signal.objects.filter(signal=signal_name).update(signal=module_path)

def make_signals_undynamic(apps, schema_editor):
    Signal = apps.get_model('dbmail', 'Signal')
    for module_path, signal_name in _SIGNALS:
        Signal.objects.filter(signal=module_path).update(signal=signal_name)

class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0014_auto_20170801_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='signal',
            field=models.CharField(default=b'django.db.models.signals.post_save', max_length=255, verbose_name='Signal', choices=list(SIGNAL_CHOICES))
        ),
        migrations.RunPython(make_signals_dynamic, make_signals_undynamic)
    ]
