# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0014_auto_20170307_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='expiry',
            field=models.PositiveIntegerField(default=120, verbose_name='Time in (s) before task expires'),
        ),
    ]
