# Generated by Django 2.2 on 2020-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0017_fix_migration_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='expiry',
            field=models.PositiveIntegerField(default=120, verbose_name='Time in (s) before task expires'),
        ),
    ]
